# pipeline de base pour s'entraîner

name: 00-learn-github-actions

# trigger pour déclencher les actions lors des push
on: [push]

#liste des jobs
jobs: 
  # 1er job
  check-bats-version:
    #def du renner (ubuntu lastversion)
    runs-on: ubuntu-latest
    # déclaration de la liste des steps
    steps:
      # action par defaut qui permet de recuperer le code du repo
      - uses: actions/checkout@v3
      # action qui permert d'installer node
      - uses: actions/setup-node@v3
        # with permet de passer des arguments
        with:
          # installer la version 14 de node
          node-version: '14'
      # run permet d'executer une commande bash
      - run: npm install -g bats
      # on utilise la commande qui retourne la version de bats
      - run: bats -v

